In [2]:
#create a 3X3X3 array with random values
import numpy as np
random_mat = np.random.random((3,3,3))
print(random_mat)

[[[0.77492914 0.77289497 0.22180367]
  [0.14040421 0.28030991 0.97369677]
  [0.09685718 0.81652093 0.5484751 ]]

 [[0.99124195 0.47362954 0.86591517]
  [0.20479745 0.50412581 0.48223466]
  [0.12698133 0.62880529 0.8572447 ]]

 [[0.93319621 0.95701625 0.70414763]
  [0.77893525 0.10375344 0.96234439]
  [0.20401944 0.19444434 0.57700538]]]


In [3]:
#create a 5X5 matrix with values 1,2,3,4 just below digonal
import numpy as np


In [4]:
#create 8X8 matrix and fill it up in chessboard pattern
import numpy as np
a = np.ones((3,3))
a = np.zeros((8,8),dtype=int)
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [5]:
#normalise 5X5 random matrix
import numpy as np
a = np.random.random((5,5))
print(a)
a_min = a.min()
a_max = a.max()
a_normalised = (a - a_min) / (a_max - a_min)
print(a_normalised)



[[0.51770314 0.34140171 0.44974831 0.21497843 0.85761539]
 [0.88866729 0.59355505 0.77130629 0.41558213 0.07249028]
 [0.50957781 0.75876366 0.64641882 0.02526717 0.5503504 ]
 [0.76984429 0.49176598 0.00316161 0.59078244 0.20961835]
 [0.9626182  0.9982415  0.5470962  0.67036253 0.04647403]]
[[0.51708564 0.33991251 0.44879481 0.21286413 0.85867857]
 [0.88988401 0.5933126  0.77194272 0.4144597  0.06967145]
 [0.50892014 0.75933808 0.64643776 0.02221486 0.54989433]
 [0.7704735  0.49102024 0.         0.59052628 0.20747755]
 [0.96420056 1.         0.54662404 0.67049985 0.04352657]]


In [7]:
#how to find common values between two arrays
import numpy as np
array_1 = [5,10,15,20]
array_2 = [3,6,15,2]
result_array = np.intersect1d(array_1,array_2)
print('common values are',result_array)

common values are [15]


In [12]:
#how to get dates of yesterday,today and tomorrow
import numpy as np
from datetime import date
from datetime import timedelta
date_today = date.today
date_yesterday = (date_today) - timedelta(days=1)
date_tomorrow = (date_today) + timedelta(days=1)
date_array = ([date_yesterday,date_today,date_tomorrow])
print(date_array)

TypeError: unsupported operand type(s) for -: 'builtin_function_or_method' and 'datetime.timedelta'

In [14]:
#consider two random arrays A and B check if they are equal
import numpy as np
a = np.random.random((1,3))
print(a)
b = np.random.random((1,3))
print(b)
common = np.intersect1d(a,b)
print(common)

[[0.86403249 0.3172132  0.96598423]]
[[0.22693083 0.79844025 0.63052881]]
[]


In [27]:
#create random vector of size 10 and replace maximum value by 0
import numpy as np
x = np.random.random((2,5))
print(x)
y = np.max(x)
print(y)
print(x)


[[0.6081454  0.19846937 0.8937292  0.58586731 0.77700043]
 [0.70330297 0.83041343 0.9762246  0.94839681 0.47059057]]
0.9762246003006159
[[0.6081454  0.19846937 0.8937292  0.58586731 0.77700043]
 [0.70330297 0.83041343 0.9762246  0.94839681 0.47059057]]


In [30]:
#how to print all values of an array 
import numpy as np
x = np.random.random((3,3))
print(x)

[[0.97738772 0.2906088  0.80698264]
 [0.2592198  0.67128883 0.07837842]
 [0.76044359 0.86314762 0.37551844]]


In [34]:
#how to get diagonal of dot product
import numpy as np
a = np.random.random((3,3))
b = np.random.random((3,3))
print(a)
print(b)
dot_product = np.dot(a,b)
print('dot_product',dot_product)
diagonal = np.diag(dot_product)
print('digonal',diagonal)

[[0.04839849 0.6750929  0.09692053]
 [0.76371032 0.72360427 0.36222664]
 [0.06420713 0.77526717 0.96699022]]
[[0.3031113  0.21515126 0.61816816]
 [0.58224829 0.35343962 0.47985478]
 [0.393311   0.25588623 0.15323759]]
dot_product [[0.44586172 0.2738182  0.36871682]
 [0.7952743  0.51275247 0.87483311]
 [0.85118779 0.53526386 0.55988571]]
digonal [0.44586172 0.51275247 0.55988571]


In [38]:
#how to get most frequent value in an array
import numpy as np
x = np.random.randint((6,7))
print(x)
y = np.bincount(x).argmax()
print(y)

[5 1]
1


In [40]:
#how to get n largest value from an array
import numpy as np
a = np.arange(10)
print('array:',a)
np.random.shuffle(a)
n = 1
print(a[np.argsort(a)[-n:]])

array: [0 1 2 3 4 5 6 7 8 9]
[9]


In [44]:
#how to create record array from regular array
import numpy as np
record = [
            (1, 'Alex', 12),
             (2, 'siri', 13),
             (3, 'dennis', 14),
           ]
dtype = [('ID', int), ('Name', 'U10'), ('Age', int)]
result = np.array(record, dtype=dtype)
print(result)
print("ID:", result['ID'])
print("Name:", result['Name'])
print("Age:", result['Age'])



[(1, 'Alex', 12) (2, 'siri', 13) (3, 'dennis', 14)]
ID: [1 2 3]
Name: ['Alex' 'siri' 'dennis']
Age: [12 13 14]


In [46]:
#how to swap two rows in array
import numpy as np
a = np.random.random((2,2))
print('a before swapping',a)
a[[1,0]]=a[[0,1]]
print('a after swapping',a)

a before swapping [[0.22200301 0.83823998]
 [0.79746686 0.73091593]]
a after swapping [[0.79746686 0.73091593]
 [0.22200301 0.83823998]]


In [48]:
#write python code to reshape to the next dimension
import numpy as np 
x=np.array([[23,34,121],[23,22,67],[686,434,123]])
print(x)
reshaped = x.reshape(x.shape[0],x.shape[1],1)
print(reshaped)

[[ 23  34 121]
 [ 23  22  67]
 [686 434 123]]
[[[ 23]
  [ 34]
  [121]]

 [[ 23]
  [ 22]
  [ 67]]

 [[686]
  [434]
  [123]]]
